### ISSUE TITLE
Crashed and lack of maintaince

### ISSUE THREAD

**Issue by dinfer** [bjjyd/shadowsocks-go#2]
It crashed when I use shadowscoks-windows(3.3.1) to connect.

```
panic: runtime error: slice bounds out of range

goroutine 35 [running]:
panic(0x5686c0, 0xc420010100)
        /home/dev/.build/go/go/src/runtime/panic.go:500 +0x1a1
shadowsocks-go/pkg/connection/tcp/ssclient.(*Client).ParseReqData(0xc420018800, 0xc42011c000, 0x1400, 0x1603, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/dev/.build/go/gopath/src/shadowsocks-go/pkg/connection/tcp/ssclient/ssclient.go:186 +0x593
shadowsocks-go/pkg/connection/tcp.PipeData.func1(0xc42005ca80, 0xc420018800, 0x1bf08eb000, 0x64c5a0, 0xc4200260a0, 0xc4200115c8)
        /home/dev/.build/go/gopath/src/shadowsocks-go/pkg/connection/tcp/pipe.go:35 +0xea
created by shadowsocks-go/pkg/connection/tcp.PipeData
        /home/dev/.build/go/gopath/src/shadowsocks-go/pkg/connection/tcp/pipe.go:51 +0xf2
```

code

``` go
fmt.Println(cap(buf), headerLen, dataEndIdx) // to print
if _, err := io.ReadFull(c, buf[headerLen:dataEndIdx]); err != nil {
    return nil, err
}

// result
5635 12 5647
```

the offset is incorrect

---

And the Dockerfile is wrong, It should build in `/cmd/shadowss/server`, not `/cmd/shadowss/`
[link](https://github.com/bjjyd/shadowsocks-go/blob/master/build/build-image/Dockerfile#L14)

**Comment by seanchann** [comment]
The next version will fix, thanks
